on:
  push:
     branches:
       - main

  

name: renderbook

jobs:
  bookdown:
    name: Render-Book
    runs-on: ubuntu-latest
    container: rocker/tidyverse:latest
    steps:
      - uses: actions/checkout@v1
      - name: get pandoc
      # note: this is hardcoded to use pandoc-2.17.1.1-amd64.deb !needs to change if the pandoc step fails!
        run: wget -O pandoc.deb https://github.com/jgm/pandoc/releases/download/2.17.1.1/pandoc-2.17.1.1-1-amd64.deb
      - name: unpack & install pandoc
        run: sudo dpkg -i pandoc.deb
      - name: install tinytex
        run: apt-get update -qq && apt-get install -y texlive
      - name: Install rmarkdown
        run: install2.r --error --deps TRUE rmarkdown
      - name: Install bookdown
        run: install2.r --error --deps TRUE bookdown
      - name: Render Book
        run: Rscript -e 'bookdown::render_book("index.Rmd")'
      - uses: actions/upload-artifact@v1
        with:
          name: _book
          path: _book/
  
# Need to first create an empty gh-pages branch
# see https://pkgdown.r-lib.org/reference/deploy_site_github.html
# and also add secrets for a GH_PAT and EMAIL to the repository
# gh-action from Cecilapp/GitHub-Pages-deploy
  checkout-and-deploy:
   runs-on: ubuntu-latest
   needs: bookdown
   steps:
     - name: Checkout
       uses: actions/checkout@master
     - name: Download artifact
       uses: actions/download-artifact@v1.0.0
       with:
         # Artifact name
         name: _book # optional
         # Destination path
         path: _book # optional
     - name: copy to _site
       run: cp -r _book/ _site/
     - name: Deploy to GitHub Pages
       uses: Cecilapp/GitHub-Pages-deploy@master
       env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # https://github.com/settings/tokens
       with:
          email: ${{ secrets.EMAIL }}               # must be a verified email
          build_dir: _site                     # "_site/" by default
          jekyll: no
          branch: gh_pages
          commit_message: auto-update of site from main, thanks Mona🐙!



    
 
